// Piece descriptions sourced from the official Pixie Chess piece cards.
// Keyed by piece.id (see PIECES in PixieTierList.jsx).
export const PIECE_DESCRIPTIONS = {
  "rocketman":       "Once per game, spend a turn to blast off to a random tile.",
  "fission-reactor": "Explodes on its 5th capture, destroying itself and all diagonally adjacent enemies.",
  "phase-rook":      "Can pass through allies, but can't capture through them.",
  "sumo-rook":       "Knocks pieces back instead of capturing.",
  "aristocrat":      "Prevents enemy pawns from promoting.",
  "basilisk":        "Paralyzes enemies it threatens, but cannot capture them.",
  "blade-runner":    "Kills only by passing through enemy pieces. The killed piece is captured a turn later.",
  "bouncer":         "This bishop can bounce off the edge of the board once per move.",
  "cardinal":        "This bishop can move one tile directly backward without capturing.",
  "dancer":          "If this piece checks the king, it may take two moves next turn. It cannot capture during them.",
  "djinn":           "Spend a turn to dissipate this piece. It reforms on the same tile the next time a piece is captured.",
  "horde-mother":    "Whenever this captures an enemy, place a non-promotable hordeling pawn anywhere on the board. If this piece or any of its hordelings die, they all die.",
  "icicle":          "Enemies adjacent for 2 turns become Frozen, costing a turn to unfreeze. Cannot capture.",
  "marauder":        "Moves like a king. Gains +2 range in every direction whenever it kills a piece.",
  "pilgrim":         "If this bishop travels 20 total squares, resurrect an allied piece.",
  "gunslinger":      "If this and an enemy piece threaten each other for a full turn, you may spend a turn to destroy them.",
  "anti-violence":   "Adjacent enemy pieces cannot capture. This piece cannot capture.",
  "banker":          "Whenever this piece captures a pawn, transform one of your pawns into a Golden Pawn.",
  "camel":           "This knight leaps 3 tiles in one direction and 1 tile to the side.",
  "electroknight":   "After moving 3 consecutive times, becomes charged, electrocuting an additional adjacent piece on capture. Charge resets on electrocution or when moving another piece.",
  "fish":            "If this moved last turn, it can also move 1 tile in any direction without capturing.",
  "pinata":          "At the start of the game, transform into a random Pixie Chess piece.",
  "knightmare":      "This piece can jump off the board.",
  "blueprint":       "At the start of the game, transform into the pawn to its left.",
  "epee-pawn":       "Can en passant any pawn anywhere on the board.",
  "golden-pawn":     "If this pawn promotes, win the game.",
  "hero-pawn":       "If this pawn checks the enemy king, immediately promote.",
  "iron-pawn":       "Invulnerable, can't capture or promote.",
  "pawn-with-knife": "Has +1 diagonal capture range towards the center of the board.",
  "shrike":          "On its first move, captures any piece in its path when moving forward 2 tiles.",
  "war-automaton":   "Automatically moves forward 1 tile whenever a piece dies.",
  "warp-jumper":     "Can jump through any pawn.",
};
